const STACK_LOGIN_SCREEN = 0;
const STACK_TAB_SCREEN = 1;
const STACK_DETAILS_SCREEN = 2;
const TAB_SCREEN_DASHBOARD = 0;
const TAB_SCREEN_COLLECTION = 1;
const TAB_SCREEN_SETTING = 2;

const nav = {
  STACK_LOGIN_SCREEN,
  STACK_TAB_SCREEN,
  STACK_DETAILS_SCREEN,
  TAB_SCREEN_DASHBOARD,
  TAB_SCREEN_COLLECTION,
  TAB_SCREEN_SETTING,
};

export default nav;
